service: ImageResizing
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: DEVELOPMENT
  region: ap-northeast-2
  environment:
    TZ: "Asia/Seoul"

functions:
  sayHello:
    handler: src/image-resize/handler.helloLambdaWorld
