service: ImageResizing
plugins:
  - serverless-plugin-typescript

provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: nodejs14.x
  stage: DEVELOPMENT
  region: ap-northeast-2
  environment:
    TZ: "Asia/Seoul"
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}

functions:
  resize:
    handler: src/image-resize/handler.upload
