service: ImageResizing
plugins:
  - serverless-plugin-typescript

provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: nodejs14.x
  stage: DEVELOPMENT
  region: ap-northeast-2
  environment:
    TZ: "Asia/Seoul"
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  resize:
    handler: src/image-resize/handler.upload
