service: ImageResizing
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - "web/**"
provider:
  name: aws
  runtime: nodejs14.x
  stage: DEVELOPMENT
  region: ap-northeast-2
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    TZ: "Asia/Seoul"
    AWS_S3_ACCESS_KEY_ID: ${env:AWS_S3_ACCESS_KEY_ID}
    AWS_S3_SECRET_ACCESS_KEY: ${env:AWS_S3_SECRET_ACCESS_KEY}
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}

functions:
  resize:
    handler: src/image-resize/handler.upload
    events:
      - http:
          path: upload
          method: post
          cors: true
