service: ImageResizing
plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - "web/**"
provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: nodejs14.x
  stage: DEVELOPMENT
  region: ap-northeast-2
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  environment:
    TZ: "Asia/Seoul"
    AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            - Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - ${env:AWS_S3_BUCKET}
                  - "/*"

functions:
  resize:
    handler: src/image-resize/handler.upload
    events:
      - http:
          path: upload
          method: post
          cors: true
